# Generated by Django 5.0.7 on 2024-08-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='password',
        ),
    ]
