# Generated by Django 5.0.7 on 2024-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_remove_blog_last_login_remove_blog_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
