# Generated by Django 5.0.7 on 2024-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_alter_blog_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksAndBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('BOOK', 'Books'), ('BRO', 'Brochure')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='books/image')),
                ('YOP', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('view', models.PositiveIntegerField()),
                ('read', models.PositiveIntegerField()),
            ],
        ),
    ]
