# Generated by Django 5.0.7 on 2024-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_booksandbrochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksandbrochure',
            name='book',
            field=models.FileField(default='', upload_to='books/pdf'),
        ),
    ]
